In [7]:
import pandas as pd
df = pd.read_json("titanic.json")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,None,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,None,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,None,C

In [12]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\divya\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\divya\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [15]:
import pandas as pd

df = pd.read_excel("Supermarket-Sales-Sample-Data.xlsx")
df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Supermarket Sales Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tax,0.1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD)
7,NaN,1001,2024-01-01 00:00:00,John Smith,2024-01-03 00:00:00,49.99,2,9.998,109.978
8,NaN,1002,2024-01-01 00:00:00,Jane Doe,2024-01-04 00:00:00,29.99,1,2.999,32.989
9,NaN,1003,2024-01-02 00:00:00,Michael Johnson,2024-01-07 00:00:00,99.99,3,29.997,329.967

In [15]:
import pandas as pd
df = pd.read_json("titanic.json")
print(df)
df.head()
# Used to identify missing values
print(df.isnull())
#count missing values for all field
df.isnull().sum()
#Find rows having missing age
df[df["Age"].isnull()]
#fill age with mean
ma = df["Age"].mean()
df["Age"] = df["Age"].fillna(ma)
# by using mode() means the most frequently occurring value in a column
me = df["Embarked"].mode()[0]
df['Embarked'] = df['Embarked'].fillna(me)
#dropna()
#Remove rows
df.dropna()
#remove column
df.dropna(axis = 1)
#you need specific row and column
print(df.iloc[0:5,1:3])

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]
   Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3

In [2]:
import pandas as pd
#change my index to customer id
df = pd.read_csv('customers-100.csv', index_col= 'Customer Id')
print(df)
#acessing specific columns for particular index 
print(df.loc['053d585Ab6b3159', ['First Name', 'Company']])
#range from this to that
print(df.loc['cb8E23e48d22Eae': '2354a0E336A91A1', ['First Name', 'Company']])
"""#Groupby
#Average fare per class
print(df.groupby('Pclass')['Fare'].mean())
#count survivors by gender
df.groupby('Sex')['Survived'].sum()
# multiple aggregations
print(df.groupby('Pclass').agg({'Age':['mean','min','max'],'Fare':['mean','sum']}))
#Add class average fare
df['Avg_Class_Fare'] = df.groupby('Pclass')['Fare']"""

                 Index First Name Last Name                          Company  \
Customer Id
DD37Cf93aecA6Dc      1     Sheryl    Baxter                  Rasmussen Group
1Ef7b82A4CAAD10      2    Preston    Lozano                      Vega-Gentry
6F94879bDAfE5a6      3        Roy     Berry                    Murillo-Perry
5Cef8BFA16c5e3c      4      Linda     Olsen  Dominguez, Mcmillan and Donovan
053d585Ab6b3159      5     Joanna    Bender         Martin, Lang and Andrade
...                ...        ...       ...                              ...
cb8E23e48d22Eae     96       Karl     Greer                        Carey LLC
CeD220bdAaCfaDf     97       Lynn  Atkinson            Ware, Burns and Oneal
28CDbC0dFe4b1Db     98       Fred    Guerra                    Schmitt-Jones
c23d1D9EE8DEB0A     99     Yvonne    Farmer               Fitzgerald-Harrell
2354a0E336A91A1    100   Clarence    Haynes               Le, Nash and Cross

                              City                     Country  \
Customer Id
DD37Cf93aecA6Dc       East Leonard                       Chile
1Ef7b82A4CAAD10  East Jimmychester                    Djibouti
6F94879bDAfE5a6      Isabelborough         Antigua and Barbuda
5Cef8BFA16c5e3c         Bensonview          Dominican Republic
053d585Ab6b3159     West Priscilla  Slovakia (Slovak Republic)
...                            ...                         ...
cb8E23e48d22Eae       East Richard                      Guyana
CeD220bdAaCfaDf       New Bradview                   Sri Lanka
28CDbC0dFe4b1Db         Ortegaland             Solomon Islands
c23d1D9EE8DEB0A    Lake Elijahview                       Aruba
2354a0E336A91A1          Judymouth                    Honduras

                                Phone 1                 Phone 2  \
Customer Id
DD37Cf93aecA6Dc            229.077.5154        397.884.0519x718
1Ef7b82A4CAAD10              5153435776        686-620-1820x944
6F94879bDAfE5a6         +1-539-402-0259     (496)978-3969x58947
5Cef8BFA16c5e3c  001-808-617-6467x12895         +1-813-324-8756
053d585Ab6b3159  001-234-203-0635x76146   001-199-446-3860x3486
...                                 ...                     ...
cb8E23e48d22Eae     (188)169-1674x58692    001-841-293-3519x614
CeD220bdAaCfaDf         +1-846-706-2218            605.413.3198
28CDbC0dFe4b1Db    +1-753-067-8419x7170   +1-632-666-7507x92121
c23d1D9EE8DEB0A           (530)311-9786  001-869-452-0943x12424
2354a0E336A91A1           (753)813-6941            783.639.1472

                                          Email Subscription Date  \
Customer Id
DD37Cf93aecA6Dc        zunigavanessa@smith.info        2020-08-24
1Ef7b82A4CAAD10                 vmata@colon.com        2021-04-23
6F94879bDAfE5a6             beckycarr@hogan.com        2020-03-25
5Cef8BFA16c5e3c     stanleyblackwell@benson.org        2020-06-02
053d585Ab6b3159         colinalvarado@miles.net        2021-04-17
...                                         ...               ...
cb8E23e48d22Eae                hhart@jensen.com        2022-01-30
CeD220bdAaCfaDf               vkemp@ferrell.com        2021-07-10
28CDbC0dFe4b1Db                swagner@kane.org        2021-09-18
c23d1D9EE8DEB0A  mccarthystephen@horn-green.biz        2021-08-11
2354a0E336A91A1          colleen91@faulkner.biz        2020-03-11

                                           Website
Customer Id
DD37Cf93aecA6Dc         http://www.stephenson.com/
1Ef7b82A4CAAD10              http://www.hobbs.com/
6F94879bDAfE5a6           http://www.lawrence.com/
5Cef8BFA16c5e3c         http://www.good-lyons.com/
053d585Ab6b3159        https://goodwin-ingram.com/
...                                            ...
cb8E23e48d22Eae            http://hayes-perez.com/
CeD220bdAaCfaDf         https://novak-allison.com/
28CDbC0dFe4b1Db              https://www.ross.com/
c23d1D9EE8DEB0A               http://watkins.info/
2354a0E336A91A1  http://www.hatfield-saunders.net/

[100 rows x 11 columns]
First Name                      Joanna
Company       Martin, Lang and Andrade
Name: 053d585Ab6b3159, dtype: object
                First Name                Company
Customer Id
cb8E23e48d22Eae       Karl              Carey LLC
CeD220bdAaCfaDf       Lynn  Ware, Burns and Oneal
28CDbC0dFe4b1Db       Fred          Schmitt-Jones
c23d1D9EE8DEB0A     Yvonne     Fitzgerald-Harrell
2354a0E336A91A1   Clarence     Le, Nash and Cross

"#Groupby\n#Average fare per class\nprint(df.groupby('Pclass')['Fare'].mean())\n#count survivors by gender\ndf.groupby('Sex')['Survived'].sum()\n# multiple aggregations\nprint(df.groupby('Pclass').agg({'Age':['mean','min','max'],'Fare':['mean','sum']}))\n#Add class average fare\ndf['Avg_Class_Fare'] = df.groupby('Pclass')['Fare']"

In [6]:
import pandas as pd

# interpolate()
# Estimate missing values.

sample = pd.DataFrame({
    'Age': [20, 25, None, 35, 40]
})

sample['Age'] = sample['Age'].interpolate()

print(sample)

    Age
0  20.0
1  25.0
2  30.0
3  35.0
4  40.0

In [19]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

#1. INNER MERGE
inner_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="inner"
)

print(inner_merge.head())
print(inner_merge.shape)
#2. LEFT MERGE
left_df = pd.merge(
    students,
    marks,
    on = "Student_ID",
    how = "left"
)
print(left_df.tail())
#Even if marks are missing,students remain.
#3. RIGHT MERGE

right_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

print(right_merge.head())
#4. OUTER MERGE

outer_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)
print(outer_merge.tail())

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60
(45, 5)
    Student_ID        Name Department  Maths  Python
45        1046  Student_46        CSE    NaN     NaN
46        1047  Student_47         IT    NaN     NaN
47        1048  Student_48        ECE    NaN     NaN
48        1049  Student_49        EEE    NaN     NaN
49        1050  Student_50       MECH    NaN     NaN
   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60
    Student_ID Name Department  Maths  Python
50        2001  NaN        NaN   75.0    80.0
51        2002  NaN        NaN   75.0    80.0
52        2003  NaN        NaN   75.0    80.0
53        2004  NaN        NaN   75.0    80.0
54        2005  NaN        NaN   75.0    80.0

In [8]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

#5. Combine Students, Marks, and Contact

combined_data = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

combined_data = pd.merge(
    combined_data,
    contact,
    on="Student_ID",
    how="left"
)

print(combined_data.head())
print(combined_data.shape)

   Student_ID       Name Department  Maths  Python                 Email
0        1001  Student_1        CSE   61.0    56.0  student1@college.edu
1        1002  Student_2         IT   62.0    57.0  student2@college.edu
2        1003  Student_3        ECE   63.0    58.0  student3@college.edu
3        1004  Student_4        EEE   64.0    59.0  student4@college.edu
4        1005  Student_5       MECH   65.0    60.0  student5@college.edu
(50, 6)

In [9]:
# 6. CONCAT ROW-WISE
# Split students into two parts.
part1 = students.iloc[:25]
part2 = students.iloc[25:]
c_r = pd.concat([part1,part2])
print(c_r.shape)

(50, 3)

In [10]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")
# 7. CONCAT COLUMN-WISE
     
student_basic = students[['Student_ID', 'Name']]
student_marks = marks[['Python']]

combined_cols = pd.concat(
    [student_basic, student_marks],
    axis=1
)

print(combined_cols.head())

   Student_ID       Name  Python
0        1001  Student_1      56
1        1002  Student_2      57
2        1003  Student_3      58
3        1004  Student_4      59
4        1005  Student_5      60

In [12]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")
#8. JOIN()

#join() works using indexes.

students_index = students.set_index("Student_ID")
contact_index = contact.set_index("Student_ID")

joined_df = students_index.join(contact_index)

print(joined_df.tail(10))

                  Name Department                  Email
Student_ID
1041        Student_41        CSE  student41@college.edu
1042        Student_42         IT  student42@college.edu
1043        Student_43        ECE  student43@college.edu
1044        Student_44        EEE  student44@college.edu
1045        Student_45       MECH  student45@college.edu
1046        Student_46        CSE  student46@college.edu
1047        Student_47         IT  student47@college.edu
1048        Student_48        ECE  student48@college.edu
1049        Student_49        EEE  student49@college.edu
1050        Student_50       MECH  student50@college.edu

### Pivot Files

In [13]:
"""A Pivot table is used to summarize and analyse data by grouping rows and applaying aggregate functions such as sum, mean, count, max,min etc."""
#step 1: load dataset
import pandas as pd
df = pd.read_csv("people-100.csv")
print(df.head())
# step 2 : Create age column
df['Date of birth']  = pd.to_datetime(df['Date of birth'])
today = pd.Timestamp.today()
df['Age'] = ((today - df["Date of birth"]).dt.days // 365)
print(df[["First Name","Sex","Age"]].head())

   Index          User Id First Name Last Name     Sex  \
0      1  88F7B33d2bcf9f5     Shelby   Terrell    Male
1      2  f90cD3E76f1A9b9    Phillip   Summers  Female
2      3  DbeAb8CcdfeFC2c   Kristine    Travis    Male
3      4  A31Bee3c201ef58    Yesenia  Martinez    Male
4      5  1bA7A3dc874da3c       Lori      Todd    Male

                        Email                   Phone Date of birth  \
0        elijah57@example.net  001-084-906-7849x73518    1945-10-26
1       bethany14@example.com       214.112.6044x4913    1910-03-24
2       bthompson@example.com            277.609.7938    1992-07-02
3   kaitlinkaiser@example.com            584.094.6111    2017-08-03
4  buchananmanuel@example.net       689-207-3558x7233    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon
  First Name     Sex  Age
0     Shelby    Male   80
1    Phillip  Female  116
2   Kristine    Male   33
3    Yesenia    Male    8
4       Lori    Male   87

In [23]:
# 1.Basic pivot 
# Average age by gender
pivot1 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex"
)
print(pivot1)
# 2. Pivot table with aggfunc = 'mean'
pivot2 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex",
    aggfunc = 'mean'
)
print(pivot2)
# 3. Pivot table with aggfunc = 'sum'
pivot3 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex",
    aggfunc = 'sum'
)
print(pivot3)
# 4. Pivot table with aggfunc = 'count'
pivot4 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex",
    aggfunc = 'count'
)
print(pivot4)
# 5. Multiple aggregate function
pivot5 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex",
    aggfunc = ['mean','max','min']
)
print(pivot5)
# 6. Adds overall average
pivot6 = pd.pivot_table(
    df,
    values = "Age",
    index = "Sex",
    aggfunc = 'mean',
    margins = True
)
print(pivot6)
# 7. Group by Job title and gender
# Average age by job title and gender
pivot7 = pd.pivot_table(
    df,
    values = "Age",
    index = "Job Title",
    columns = "Sex",
    aggfunc = 'mean',
)
print(pivot7)
# Count People by John and Gender
pivot8 = pd.pivot_table(
    df,
    values = "User Id",
    index = "Job Title",
    columns = "Sex",
    aggfunc = "count",
    fill_value = 0
)
print(pivot8)
#nan fill value with 0

              Age
Sex
Female  64.981132
Male    54.957447
              Age
Sex
Female  64.981132
Male    54.957447
         Age
Sex
Female  3444
Male    2583
        Age
Sex
Female   53
Male     47
             mean  max min
              Age  Age Age
Sex
Female  64.981132  117   8
Male    54.957447  117   5
              Age
Sex
Female  64.981132
Male    54.957447
All     60.270000
Sex                               Female   Male
Job Title
Accountant, chartered management    95.0   88.0
Accounting technician               17.0    NaN
Advertising account executive       18.0    NaN
Agricultural consultant              NaN   34.0
Air broker                          84.0    NaN
...                                  ...    ...
Travel agency manager                NaN  117.0
Veterinary surgeon                   NaN   87.0
Warden/ranger                        NaN   45.0
Warehouse manager                    NaN  101.0
Waste management officer             NaN   10.0

[91 rows x 2 columns]
Sex                               Female  Male
Job Title
Accountant, chartered management       1     1
Accounting technician                  1     0
Advertising account executive          1     0
Agricultural consultant                0     1
Air broker                             1     0
...                                  ...   ...
Travel agency manager                  0     1
Veterinary surgeon                     0     1
Warden/ranger                          0     1
Warehouse manager                      0     1
Waste management officer               0     1

[91 rows x 2 columns]

In [25]:
import pandas as pd
df = pd.read_excel("Data_Cleaning_50Plus_Records.xlsx")
print(df.head())
print(df.columns)

   Student ID Student Name   Department   Age   Salary               Email
0         101      student1          IT  20.0  23075.0  student1@gmail.com
1         102      student2         ECE  18.0  35929.0  student2@gmail.com
2         103      STUDENT3         EEE  22.0  29718.0  student3@gmail.com
3         104      student4        MECH  20.0  21009.0  student4@gmail.com
4         105     Student5          CSE  19.0  47113.0  student5@gmail.com
Index(['Student ID', 'Student Name ', ' Department', 'Age', 'Salary', 'Email'], dtype='object')

In [43]:
#2. Renaming columns
# check current column names
print(df.columns)
df.rename(columns = {
    'Student ID': "Student_ID",
    'Student Name ': 'Student_Name',
    ' Department': 'Department'},inplace = True)
print(df.columns)
print(df.dtypes)

Index(['Student_ID', 'Student_Name', 'Department', 'Age', 'Salary', 'Email'], dtype='object')
Index(['Student_ID', 'Student_Name', 'Department', 'Age', 'Salary', 'Email'], dtype='object')
Student_ID       object
Student_Name     object
Department       object
Age               int64
Salary          float64
Email            object
dtype: object

In [44]:
#3. Convert Student_ID to String

df['Student_ID'] = df['Student_ID'].astype(str)

# Convert Age to Integer
# First handle missing values

df['Age'] = df['Age'].fillna(0)

df['Age'] = df['Age'].astype(int)

# Check Data Types

print(df.dtypes)

Student_ID       object
Student_Name     object
Department       object
Age               int64
Salary          float64
Email            object
dtype: object

In [28]:
#4. Detect Duplicate Records

duplicates = df.duplicated()

print(duplicates)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
dtype: bool

In [29]:
import pandas as pd
df = pd.read_excel("Data_Cleaning_50Plus_Records.xlsx")
# Count duplicates
print(df.duplicated().sum())

0

In [30]:
# 5. Dropping Duplicate records
#before
print(df.shape)
#remove duplicates
df.drop_duplicates(inplace = True)
#After
print(df.shape)

(52, 6)
(52, 6)

In [46]:
# 6. String operations
# String methods work only on text columns
# Remove Extra space
df['Student_Name'] = df['Student_Name'].str.strip()
# Convert to Uppercase
df['Student_Name'] = df['Student_Name'].str.upper()
print(df['Student_Name'].head())
#Convert to title case
df['Student_Name'] = df['Student_Name'].str.title()
print(df['Student_Name'].head())

#Replace text
#replace department name
df['Department'] = df['Department'].replace({
    'CSE':'Computer Science',
    'ECE': 'Electronics and communi eng',
    'EEE': 'electircal and electronic',
    'IT': 'Information tech',
    'MECH' : 'Mechanical'
})
print(df['Department'].head())
print(df.columns)

0    STUDENT1
1    STUDENT2
2    STUDENT3
3    STUDENT4
4    STUDENT5
Name: Student_Name, dtype: object
0    Student1
1    Student2
2    Student3
3    Student4
4    Student5
Name: Student_Name, dtype: object
0                       Information Technology
1    Electronics and Communication Engineering
2       Electrical and Electronics Engineering
3                       Mechanical Engineering
4                 Computer Science Engineering
Name: Department, dtype: object
Index(['Student_ID', 'Student_Name', 'Department', 'Age', 'Salary', 'Email'], dtype='object')

In [49]:
#String length
df['Name_Length'] = df['Student_Name'].str.len()
print(df[['Student_Name','Name_Length']].head())
#Extra First character
df['First_Letter'] = df['Student_Name'].str[0]
print(df[['Student_Name','First_Letter']].head())

  Student_Name  Name_Length
0     Student1            8
1     Student2            8
2     Student3            8
3     Student4            8
4     Student5            8
  Student_Name First_Letter
0     Student1            S
1     Student2            S
2     Student3            S
3     Student4            S
4     Student5            S